[package]
name = "{{PACKAGE_NAME}}"
version = "0.1.0"
alya-version = "0.0.19"
entry = "src/lib.alya"
description = "{{DESCRIPTION}}"
authors = ["Alya Language Contributors <https://github.com/alya-lang>"]
license = "MIT"
homepage = "https://github.com/alya-lang/alya"
repository = "https://github.com/alya-lang/{{PACKAGE_NAME}}"
keywords = ["alya", "alya-lang", "package", "{{PACKAGE_NAME}}"]

[dependencies]

# [build]
# c-sources = ["c/source.c"]
# c-flags = ["-O2"]
# c-include-dirs = ["c"]
# links = "{{PACKAGE_NAME}}"

# [lint]
# disabled_rules = []
# exclude = []

# [fmt]
# exclude = []

# [test]
# exclude = []

# [bench]
# exclude = []
